### ISSUE TITLE
单个文件上传，支持的最大大小？

### ISSUE THREAD

**Issue by solfx** [Y0LANDA/NoHttp#190]
模仿 simple 中的单文件上传方式，上传一个大约 370MB 左右文件。
会 OOM，内存快照，看到字节数组异常的大。
![wx20180717-115006](https://user-images.githubusercontent.com/20767341/42795575-a2e867dc-89b7-11e8-9179-ca0a87c0519f.png)

是我的使用方式有问题，还是 byte[] 没有释放？

**Comment by solfx** [comment]
OOM异常堆栈信息如下：
07-17 13:50:06.549 27422-27682/com.yuancore.cmskit E/AndroidRuntime: FATAL EXCEPTION: Thread-3409
    Process: com.yuancore.cmskit, PID: 27422
    java.lang.OutOfMemoryError: Failed to allocate a 8204 byte allocation with 1872 free bytes and 1872B until OOM
        at okio.Segment.<init>(Segment.java:63)
        at okio.SegmentPool.take(SegmentPool.java:48)
        at okio.Buffer.writableSegment(Buffer.java:1217)
        at okio.Buffer.write(Buffer.java:1018)
        at okio.Buffer.write(Buffer.java:54)
        at okhttp3.internal.huc.OutputStreamRequestBody$1.write(OutputStreamRequestBody.java:64)
        at java.io.BufferedOutputStream.flushInternal(BufferedOutputStream.java:185)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:139)
        at com.yanzhenjie.nohttp.BasicBinary.onWriteBinary(BasicBinary.java:101)
        at com.yanzhenjie.nohttp.BasicRequest.writeFormBinary(BasicRequest.java:1105)
        at com.yanzhenjie.nohttp.BasicRequest.writeFormStreamData(BasicRequest.java:1071)
        at com.yanzhenjie.nohttp.BasicRequest.onWriteRequestBody(BasicRequest.java:1032)
        at com.yanzhenjie.nohttp.HttpConnection.writeRequestBody(HttpConnection.java:181)
        at com.yanzhenjie.nohttp.HttpConnection.createConnectionAndWriteData(HttpConnection.java:130)
        at com.yanzhenjie.nohttp.HttpConnection.getConnection(HttpConnection.java:75)
        at com.yanzhenjie.nohttp.rest.RequestHandler.getHttpProtocol(RequestHandler.java:176)
        at com.yanzhenjie.nohttp.rest.RequestHandler.requestCacheOrNetwork(RequestHandler.java:138)
        at com.yanzhenjie.nohttp.rest.RequestHandler.handle(RequestHandler.java:73)
        at com.yanzhenjie.nohttp.rest.SyncRequestExecutor.execute(SyncRequestExecutor.java:46)
        at com.yanzhenjie.nohttp.rest.RequestDispatcher.run(RequestDispatcher.java:88)

**Comment by autismbug92** [comment]
okhttp 中有个 issue ，和这个问题一样。
[https://github.com/cloudinary/cloudinary_java/issues/55](okhttp issue)
okhttp 中有没有把作者的修复同步过来
