### ISSUE TITLE
1.1.11请求后App崩溃

### ISSUE THREAD

**Issue by WhoIsAA** [Y0LANDA/NoHttp#198]
换回1.1.10就不会有这个问题，但是1.1.10又存在**Attempt to invoke virtual method 'void com.yanzhenjie.nohttp.rest.Messenger.start()' on a null object reference**问题，1.1.11崩溃日志如下：

```
09-06 15:14:27.090 20563-20563/com.example.test E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.test, PID: 20563
    java.lang.NullPointerException: Attempt to invoke interface method 'void com.yanzhenjie.nohttp.rest.OnResponseListener.onStart(int)' on a null object reference
        at com.yanzhenjie.nohttp.rest.RequestQueue$AsyncCallback$1.run(RequestQueue.java:166)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by yanzhenjie** [comment]
你是不是传了一个空的listener进去？

**Comment by WhoIsAA** [comment]
刚检查了代码，确实是有个地方传了Listener为null，在这里做下判空重新new一个就好了
