### ISSUE TITLE
The lock is null.

### ISSUE THREAD

**Issue by svran** [Y0LANDA/NoHttp#202]
The lock is null.

com.yanzhenjie.nohttp.rest.Work.run(Work.java:59)

升级1.1.11出现频繁.

**Comment by BadDeveloper2022** [comment]
1

**Comment by BadDeveloper2022** [comment]
java.lang.IllegalStateException: The lock is null.
        at com.yanzhenjie.nohttp.rest.Work.run(Work.java:59)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:848)

**Comment by log225** [comment]
1

**Comment by linghushaohong** [comment]
1

**Comment by ghost** [comment]
一样的问题，求解决

**Comment by hebin1016** [comment]
1
