### ISSUE TITLE
UnKnownHostError: Hostname can not be resolved

### ISSUE THREAD

**Issue by SherlockGougou** [Y0LANDA/NoHttp#217]
最新版本：
在某些机型上（坚果R1），几乎百分百遇到这个问题，经排查，url没有问题，可以直接浏览器访问。

```
com.yanzhenjie.nohttp.error.UnKnownHostError: Hostname can not be resolved: http://apiv4.yangkeduo.com/reviews/7611321309?ranNum=RMOOMAHbAHY&sign=fb299ea6fd7717a2aebcd374258d9c02&fromType=2&b=4662b6f46eb20583befe04d72a4ca8b7.
        at com.yanzhenjie.nohttp.HttpConnection.getConnection(HttpConnection.java:93)
        at com.yanzhenjie.nohttp.rest.RequestHandler.getHttpProtocol(RequestHandler.java:176)
        at com.yanzhenjie.nohttp.rest.RequestHandler.requestCacheOrNetwork(RequestHandler.java:120)
        at com.yanzhenjie.nohttp.rest.RequestHandler.handle(RequestHandler.java:73)
        at com.yanzhenjie.nohttp.rest.SyncRequestExecutor.execute(SyncRequestExecutor.java:46)
        at com.yanzhenjie.nohttp.rest.Worker.call(Worker.java:34)
        at com.yanzhenjie.nohttp.rest.Worker.call(Worker.java:23)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.yanzhenjie.nohttp.rest.Work.run(Work.java:65)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by SherlockGougou** [comment]
测试连接：
http://apiv4.yangkeduo.com/reviews/7611321309?ranNum=RMOOMAHbAHY&sign=fb299ea6fd7717a2aebcd374258d9c02&fromType=2&b=4662b6f46eb20583befe04d72a4ca8b7
