### ISSUE TITLE
报错 v1.1.11

### ISSUE THREAD

**Issue by wanghailong0526** [Y0LANDA/NoHttp#226]
2019-05-25 10:44:41.217 14387-14768/com.juzifenqi.app E/NoHttpLogger: java.io.InterruptedIOException
        at okhttp3.internal.huc.OkHttpURLConnection.connect(OkHttpURLConnection.java:138)
        at com.yanzhenjie.nohttp.OkHttpNetworkExecutor.execute(OkHttpNetworkExecutor.java:72)
        at com.yanzhenjie.nohttp.HttpConnection.createNetwork(HttpConnection.java:167)
        at com.yanzhenjie.nohttp.HttpConnection.createConnectionAndWriteData(HttpConnection.java:120)
        at com.yanzhenjie.nohttp.HttpConnection.getConnection(HttpConnection.java:75)
        at com.yanzhenjie.nohttp.rest.RequestHandler.getHttpProtocol(RequestHandler.java:176)
        at com.yanzhenjie.nohttp.rest.RequestHandler.requestCacheOrNetwork(RequestHandler.java:138)
        at com.yanzhenjie.nohttp.rest.RequestHandler.handle(RequestHandler.java:73)
        at com.yanzhenjie.nohttp.rest.SyncRequestExecutor.execute(SyncRequestExecutor.java:46)
        at com.yanzhenjie.nohttp.rest.Worker.call(Worker.java:34)
        at com.yanzhenjie.nohttp.rest.Worker.call(Worker.java:23)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at com.yanzhenjie.nohttp.rest.Work.run(Work.java:65)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)

**Comment by isliuqihang** [comment]
我也遇到了  请问老哥有解决方案吗
